2018-07-19 00:41:42,337 ERROR: Exception on /edit_protocols/0-irm_1-neuroradiologie_2-cerveau_3-ischemie_4-scanner_5-salle-a-ge-1-5t [GET] [in /Users/eleyine/virtualenvs/Protocols/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/eleyine/virtualenvs/Protocols/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/eleyine/virtualenvs/Protocols/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/eleyine/virtualenvs/Protocols/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eleyine/virtualenvs/Protocols/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/eleyine/virtualenvs/Protocols/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/eleyine/virtualenvs/Protocols/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/eleyine/virtualenvs/Protocols/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/eleyine/Dropbox/Coursework/Med/Extracurriculars/ProtocolsEileen/container/app/main/routes.py", line 488, in edit_protocols
    return render_template('edit_protocols.html', form=form, title=title)
  File "/Users/eleyine/virtualenvs/Protocols/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/eleyine/virtualenvs/Protocols/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/eleyine/virtualenvs/Protocols/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/eleyine/virtualenvs/Protocols/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/eleyine/virtualenvs/Protocols/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eleyine/virtualenvs/Protocols/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/eleyine/Dropbox/Coursework/Med/Extracurriculars/ProtocolsEileen/container/app/templates/edit_protocols.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/eleyine/Dropbox/Coursework/Med/Extracurriculars/ProtocolsEileen/container/app/templates/base.html", line 65, in top-level template code
    {% block content %}
  File "/Users/eleyine/Dropbox/Coursework/Med/Extracurriculars/ProtocolsEileen/container/app/templates/base.html", line 76, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/eleyine/Dropbox/Coursework/Med/Extracurriculars/ProtocolsEileen/container/app/templates/edit_protocols.html", line 29, in block "app_content"
    {% for subfield in field %}
TypeError: 'CSRFTokenField' object is not iterable
